{
  inputs,
  pkgs,
  system,
  ...
}:

let
  apiKeyFilepath = "file.token";
  result = inputs.home-manager-unstable.lib.homeManagerConfiguration {
    pkgs = import inputs.nixpkgs-unstable {
      inherit system;
      config.allowUnfree = true;
      overlays = [
        inputs.self.overlays.flake
      ];
    };
    modules = [
      inputs.self.homeManagerModules.claude-install
      {
        home.stateVersion = "25.11";
        home.username = "jdoe";
        home.homeDirectory = "/test";
        programs.claude-code = {
          enable = true;
          mcps.buildkite = {
            enable = true;
            inherit apiKeyFilepath;
          };
        };
      }
    ];
  };
in
{
  tests = [
    {
      name = "command should not have override";
      type = "script";
      script = ''
        set -x
        # Gather the mcp config file that gets generated by home-manager claude-code module.
        cat ${result.config.programs.claude-code.finalPackage}/bin/claude | ${pkgs.gnugrep}/bin/grep mcp-config
        if [ $? -eq 0 ]; then
           echo "claude binary has an --mcp-config override when it shouldn't" 
           exit 1
        fi
      '';
    }
    {
      name = "activation script should be present";
      type = "unit";
      expected = true;
      actual = result.config.home.activation ? mcpSync;
    }
    {
      name = "activation script should contain configured mcp server";
      type = "script";
      script = ''
        SCRIPT="$(echo "${pkgs.lib.trim result.config.home.activation.mcpSync.data}")"
        cat $SCRIPT | ${pkgs.gnugrep}/grep "${result.config.programs.claude-code.mcps.buildkite.mcpServer.command}"
        if [ $? -eq 1 ]; then
           echo "mcpSync script should contain command from mcp server" 
           exit 1
        fi
      '';
    }
  ];
}
